comparison_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),
    path('manage/', include('manage.urls'))
]

if settings_dev.DEBUG:
    urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .import views
from comparison_project import settings_common, settings_dev
from django.contrib.staticfiles.urls import static

app_name = 'project'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('word_detail/<int:pk>/', views.WordDetailView.as_view(), name="word_detail"),
    path('word_update/<int:pk>/', views.WordUpdateView.as_view(), name="word_update"),
    path('word_delete/<int:pk>/', views.WordDeleteView.as_view(), name="word_delete"),
    path('wordpost_create', views.WordCreateView.as_view(), name="wordpost_create"),
    path('wordreiew_list', views.WordReiewListView.as_view(), name="wordreiew_list"),
    path('wordreiew_list_like', views.WordReiewList_LikeView.as_view(), name="wordreiew_list_like"),
    path('search_advanced/', views.SearchAdvancedView.as_view(), name="search_advanced"),
    path('shop/<slug:category_slug>/', views.ProductListView.category_list, name='category_list'),
    path('product_list/', views.ProductListView.product_all, name="product_list"),
    path('product_detail/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('search_result/', views.get_queryset, name="search_result"),
    path('review/<int:pk>/', views.ReviewView.as_view(), name="review"),
    path('review_create/<slug:slug>/', views.ReviewCreateView.as_view(), name="review_create"),
    path('review_edit/<int:pk>/', views.ReviewEditView.as_view(), name="review_edit"), 
    path('review_delete/<int:pk>/', views.ReviewDeleteView.as_view(), name="review_delete"),
    path('user_review_page/<int:pk>/', views.UserReviewPageView.as_view(), name="user_review_page"),
    path('review_list/<int:pk>/', views.ReviewListView.as_view(), name="review_list"),
    path('word_list/<int:pk>/', views.WordListView.as_view(), name="word_list"),                                                                     
    path('wish_list/<int:pk>/', views.WishListView.as_view(), name="wish_list"),
    path('recently_view/<int:pk>/', views.RecentlyViewedView.as_view(), name="recently_view"),
    path('rank_list/', views.RankListView.as_view(), name="rank_list"),
    path('profile_edit/<int:pk>/', views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile_update/<int:pk>/', views.ProfileUpdateView.as_view(), name="profile_update"),
    path('Ajax_ch_word/<int:pk>/', views.Ajax_ch_word, name="Ajax_ch_word"),
    path('Ajax_ch_review/<int:pk>/', views.Ajax_ch_review, name="Ajax_ch_review"),
    path('Ajax_ch_product/<slug:slug>/', views.Ajax_ch_product, name="Ajax_ch_product"),
    path('review_product/<slug:slug>/', views.ReviewProductView.as_view(), name="review_product"),
]

if settings_dev.DEBUG:
    urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('shop/', views.IndexView.as_view(), name="shopindex"),
]

project/forms.py
from django import forms
from .models import *
from shop.models import *
from accounts.models import CustomUser
from .models import Word
from django.contrib.admin.widgets import AdminDateWidget


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('review','review_title', 'review_text', 'photo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ItemForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'description', 'image1', 'image2', 'image3',
                  'price1', 'link1', 'price2', 'link2', 'price3', 'link3',
                  'rating', 'like_product', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_photo','user_name', 'user_birthday', 'user_gender', 'user_address')
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_birthday'].widget = forms.SelectDateWidget(years=[x for x in range(1990, 2030)])
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



class WordCreateForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = ('word_title','word_text','photo',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

project/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic
from .models import Review, Recently_viewed, Wishlist
from shop.models import *
from django.shortcuts import render, get_object_or_404
from . forms import *
from django.shortcuts import redirect
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain
from django.http import JsonResponse
from django.core.paginator import Paginator

logger = logging.getLogger(__name__)


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser
    

# トップページ
class IndexView(generic.ListView):
    model = Product
    template_name = "index.html"
    context_object_name = 'user_review_list'

    # ランキング、新着口コミ情報を取り出す
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'product_list': Product.objects.all().annotate(Count('like_product')).order_by('-like_product__count', '-created_at'),
            'word_list': Word.objects.order_by('-created_at'),

        })

        return context


class SearchAdvancedView(generic.TemplateView):
    template_name = 'search_advanced.html'

class ProductListView(generic.ListView):
    model = Product, Category
    
    def categories(request):
        return {
            'categories': Category.objects.all()
        }

    def product_all(request):
        products = Product.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(products, 9)
        page_object = paginator.get_page(page)
        page_object.adjusted_elided_pages = paginator.get_elided_page_range(page)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'products': products, 
            "page_obj": page_object
        }
        return render(request, 'product_list.html', context)

    def category_list(request, category_slug=None):
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
        page = request.GET.get('page', 1)
        paginator = Paginator(products, 6)
        page_range = paginator.get_elided_page_range(number=page)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'products': products,
            'category': category, 
        }
        return render(request, 'category.html', context)



# 商品詳細ページ
class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product_detail.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        review = Review.objects.filter(productID=product.pk).order_by('-created_at')
        user = CustomUser.objects.filter(username=self.request.user)

        if user:
            wish = Wishlist.objects.filter(userID=self.request.user, wished_item=product.pk)
        else:
            wish = None

        context.update({
            'product_list': product,
            'review_list' : review,
            'wish_list' : wish,
            'like_for_post_count' : product.like_product.count()
        })

        return context
    

# 商品のいいね機能
def Ajax_ch_product(request, slug):
    """Ajax処理"""
    user = request.user
    context = {
        'user_id': f'{ request.user }',
    }

    product = Product.objects.get(slug=slug)
    wish_list = Wishlist.objects.filter(wished_item=product)
    like = False

    for wish in wish_list:
        if wish.userID == user:
            like = True

    if like == True:
        wish.delete()
        context['method'] = 'delete'
        product.like_product.remove(user)
    else:
        wish_list.create(userID=user, wished_item=product)
        context['method'] = 'create'
        product.like_product.add(user)

    context['like_for_post_count'] = product.like_product.count()
 
    return JsonResponse(context)


# 検索結果ページ
def get_queryset(request):
    # Sessionから条件取得
    params = request.session.get('params')

    if not params or request.GET.get("keyword"):
        # Sessionに値がないか、新しくキーワードから値を取得した場合、GETから取得
        params = {
            "keyword" : request.GET.get("keyword"),
            "value" : request.GET.get("value"),
            "display" : request.GET.get("display")
        }

    # Sessionに保存
    request.session['params'] = params

    if params['display'] == "popular":
        if params['value']:
            product =  Product.objects.filter(
                product_name__contains=params['keyword'],
                price1__lte=params['value']
                ).annotate(Count('like_product')).order_by('-like_product__count', '-created_at')
        else:
            product =  Product.objects.filter(
                product_name__contains=params['keyword'],
                ).annotate(Count('like_product')).order_by('-like_product__count', '-created_at')
    
    else:
        if params['value']:
            product =  Product.objects.filter(
                product_name__contains=params['keyword'],
                price1__lte=params['value']
                ).order_by('-created_at')
        else:
            product =  Product.objects.filter(
                product_name__contains=params['keyword']
                ).order_by('-created_at')
            
    # paginate_byの実装
    # 1ページに表示させる数を指定する
    count = 5

    # pagenateの実行
    paginator = Paginator(product, count)
    page = request.GET.get('page')

    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request,'search_results.html',context={'object_list':page_obj.object_list,'page_obj': page_obj})


# 口コミ詳細ページ
class WordDetailView(generic.DetailView):
    model = Word
    template_name = 'worddetail.html'


# 口コミのいいね機能
def Ajax_ch_word(request, pk):
    """Ajax処理"""
    user = request.user
    context = {
        'user_id': f'{ request.user }',
    }
    word = get_object_or_404(Word, pk=pk)
    like = False

    for like in word.like_word.all():
        if like == user:
            like = True

    if like == True:
        word.like_word.remove(user)
        context['method'] = 'delete'
    else:
        word.like_word.add(user)
        context['method'] = 'create'
 
    return JsonResponse(context)


# 口コミ情報の更新
class WordUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Word
    template_name = 'wordpost.html'
    form_class = WordCreateForm

    def get_success_url(self):
        return reverse_lazy('project:word_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '口コミを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "口コミの更新に失敗しました。")
        return super().form_invalid(form)


# 口コミ削除ページ
class WordDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Word
    template_name = 'word_delete.html'
    success_url = reverse_lazy('project:wordreiew_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "口コミを削除しました。")
        # アカウントテーブルの口コミ数を削除した状態で登録
        target_data = Word.objects.filter(created_by=self.request.user).count()
        user = CustomUser.objects.filter(username=self.request.user)
        for customuser in user:
            customuser.no_of_word = target_data
        customuser.save()
        return super().delete(request, *args, **kwargs)


# 口コミ掲示板一覧ページ
class WordReiewListView(generic.ListView):
    model = Word
    template_name = 'wordreiew_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Word.objects.order_by('-created_at')


# 口コミ掲示板(人気順)一覧ページ。ログイン中のユーザーのみ可能。
class WordReiewList_LikeView(LoginRequiredMixin,generic.ListView):
    model = Word
    template_name = 'wordreiew_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Word.objects.all().annotate(Count('like_word')).order_by('-like_word__count', '-created_at')



# 口コミ作成ページ
class WordCreateView(LoginRequiredMixin,generic.CreateView):
    model = Word
    template_name = 'wordpost.html'
    form_class = WordCreateForm
    success_url = reverse_lazy('project:wordreiew_list')

    def form_valid(self, form):
        # 口コミを登録
        word = form.save(commit=False)
        word.created_by = self.request.user
        word.save()
        # アカウントテーブルの口コミ数を登録
        target_data = Word.objects.filter(created_by=self.request.user).count()
        user = CustomUser.objects.filter(username=self.request.user)
        for customuser in user:
            customuser.no_of_word = target_data
        customuser.save()
        messages.success(self.request, '口コミを作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "口コミの作成に失敗しました。")
        return super().form_invalid(form)
       


# レビューの詳細ページ
class ReviewView(generic.DetailView):
    model = Review
    template_name = 'review.html'


# レビューのいいね機能
def Ajax_ch_review(request, pk):
    """Ajax処理"""
    user = request.user
    context = {
        'user_id': f'{ request.user }',
    }
    review = get_object_or_404(Review, pk=pk)

project/templates/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link href="{% static 'css/wordreiew_list.css' %}" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
{% endblock %}

{% block contents %}

{% if messages %}
  <ul class="list-unstyled">
    {% for message in messages %}
      <li {% if message.tags %} 
        class="bg-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert"{% endif %}>
        {{ message }}
        <button type="button" class="close" aria_label="Close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
    {% endfor %}
  </ul>
{% endif %}

 <!-- Product section 2-->
 <section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image1.url }}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">カテゴリ：{{ product.category }}</div>
                <h1 class="display-5 fw-bolder">{{ product.product_name }}</h1>
                <div class="fs-5 mb-5">
                    <!--<span class="text-decoration-line-through">$45.00</span>-->
                    <span>Rakuten価格: {{ product.price1 }} JPY</span>
                    <p><span><a href="{{ product.link1 }}"><img src="{% static 'assets/img/Rakuten.png' %}" alt="RakutenLink"></a>Rakuten店舗に飛ぶ </span></p>
                </div>
                <p class="lead">{{ product.description }}</p>
            
            {% if user.is_authenticated %}
                {% for like in wish_list %}
                    {% if like.userID == user %}
                    <button type="button" id="ajax-like" style="border:none;background:none">
                        <!-- すでにいいねしている時はfasクラス -->
                        <i class="fas fa-heart text-danger" id="like-icon"></i>
                        <span id="like-for-post-count">{{ like_for_post_count }}</span>
                        <span>件のイイね</span>
                    </button>
                    {% else %}
                    <button type="button" id="ajax-like" style="border:none;background:none">
                        <!-- いいねしていないときはfarクラス -->
                        <i class="far fa-heart text-danger" id="like-icon"></i>
                        <span id="like-for-post-count">{{ like_for_post_count }}</span>
                        <span>件のイイね</span>
                    </button>
                    {% endif %}
                {% empty %}
                    <button type="button" id="ajax-like" style="border:none;background:none">
                        <!-- いいねしていないときはfar -->
                        <i class="far fa-heart text-danger" id="like-icon"></i>
                        <span id="like-for-post-count">{{ like_for_post_count }}</span>
                        <span>件のイイね</span>
                    </button>
                {% endfor %}
            {% endif %}
        </div>
        </div>
    </div>
</section>

<div class="d-flex justify-content-end mb-4">
    <a class="btn btn-primary float-right" href="{% url 'project:review_create' object.slug %}">レビューを投稿する</a>
</div>

<div class="card mb-4">
    <div class="card-header">レビュー一覧</div>
    <div class="card-body">
        {% for review in review_list|slice:":5" %}
            <div class="container my-div-style">
                <div class="row">
                    <div class="col-9">
                        {% if review.photo %}
                        <div class="col-md-2"><img class="card-img-top mb-5 mb-md-0" src="{{ review.photo.url }}" alt="..." /></div>
                        {% else %}
                        <div class="col-md-2"><img class="card-img-top mb-5 mb-md-0" src="{% static 'assets/img/no_image.jpeg' %}" alt="..." /></div>
                        {% endif %}

                        <a href="{% url 'project:review' review.pk %}"><h6>{{ review.review_title }}</h6></a>

                        <a href="{% url 'project:user_review_page' review.created_by.pk %}">
                        <div class="inline-block_test">
                            <p>{{ review.created_by }}</p>
                        </div></a>
                        <div class="inline-block_test">
                            <p>☆{{ review.review }}</p>
                        </div>
                        <div class="inline-block_test">
                            <p>{{ review.review_text }}</p>
                        </div>

                        {% for like in review.like_review.all %}
                            {% if forloop.last == True %}
                            <td>♡{{forloop.counter}}</td>
                            {% endif %}
                            {% empty %}
                            <td>♡0</td>
                        {% endfor %}
                        
                        <hr>
                    </div>
                </div>
            </div>
        {% empty %}
        <h4>投稿されたレビューがありません。</h4>
        {% endfor %}
        {% if review_list %}
        <a class="btn btn-primary" href="{% url 'project:review_product' product.slug %}">もっと見る</a>
        {% endif %}
    </div>
    </div>
</div>
{% endblock %} 

{% block extrajs %}
<script type="text/javascript">
    // いいねボタンが押された時
    document.getElementById('ajax-like').addEventListener('click', e => {
        e.preventDefault();
        const url = '{% url "project:Ajax_ch_product" object.slug %}';
        fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
            'X-CSRFToken': '{{ csrf_token }}',
        },
        }).then(response => {
        return response.json();
        }).then(response => {
        // イイね数を書き換える
        const counter = document.getElementById('like-for-post-count')
        counter.textContent = response.like_for_post_count
        const icon = document.getElementById('like-icon')
        // いいねした時はハートを塗る
        if (response.method == 'create') {
            icon.classList.remove('far')
            icon.classList.add('fas')
            icon.id = 'like-icon'
        } else {
            icon.classList.remove('fas')
            icon.classList.add('far')
            icon.id = 'like-icon'
        }
        }).catch(error => {
        console.log(error);
        });
    });
</script>
{% endblock %}

project/templates/review_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}レビュー編集 | comparison_project{% endblock %}

{% block active_review_edit %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">保存</button>
            <a class="btn btn-primary" href="javascript:history.back()">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

project/templates/review_product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}レビュー一覧ページ | comparison_project{% endblock %}

{% block active_project_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/reiew_list.css' %}" rel="stylesheet">
<link href="{% static 'css/select.css' %}" rel="stylesheet">
{% endblock %}



{% block contents %}
<div class="col-xl-12" >
    <div class="card" style="width: 95rem;"> 
        <div class="card-body">
            <br>
            <h2>レビュー一覧</h2>
            <br> 
            {% if review_list %}   
            <table  id="dataTable" width="100%" cellspacing="50%" >
                <thead>
                    <tr>
                        <td>写真</td>
                        <td>商品名</td>
                        <td>投稿者</td>
                        <td>商品の評価</td>
                        <td>レビュータイトル</td>
                        <td>レビュー内容</td>
                        <td>いいね数</td>
                        <td>投稿日時</td>
                    </tr>
                </thead>

                <tbody>
                    {% for review in review_list %}
                        <tr>
                            <div class="inline-block_test">
                                {% if review.photo %}
                                <td><h3 class="gazo-box">
                                <img src="{{ review.photo.url }}" width="80" height="60"/>
                                </h3></td>
                                {% else %}
                                <td><h3 class="gazo-box">
                                    <img src="{% static 'assets/img/no_image.jpeg' %}" width="80" height="80" >
                                </h3></td>
                                {% endif %}
                            </div>

                            <td>
                                <a href="{% url 'project:product_detail' review.productID.slug %}">{{ review.productID|truncatechars:25 }}</a>
                            </td>

                            <td>
                                <a href="{% url 'project:user_review_page' review.created_by.pk %}">{{ review.created_by }}</a>
                            </td>

                            <td>{{ review.review }}</td>
                            <td>{{ review.review_title|truncatechars:10 }}</td>
                            <td>{{ review.review_text|truncatechars:10 }}</td>

                            {% for like in review.like_review.all %}
                                {% if forloop.last == True %}
                                <td>{{forloop.counter}}</td>
                                {% endif %}
                                {% empty %}
                                <td>0</td>
                            {% endfor %}

                            <td>{{ review.created_at }}</td>  
                        </tr>
                    {% endfor %}
                </tbody>
            </table><br>
                                
            <!-- ページネーション処理 -->
            {% if page_obj %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
            {% else %}
            <p>投稿しているレビューはありません</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

project/templates/word_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ削除 | comparison_project{% endblock %}

{% block active_prefectures_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/select.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <br>
            <h3 style="text-align:center">本当に削除しますか？</h3>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'project:word_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

project/templates/worddetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}口コミ詳細 | comparison_project{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/heart.css' %}" rel="stylesheet">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
{% endblock %}

{% block contents %}
<br>
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>タイトル</strong>
        </div>
        <div class="col-9">
            {{ word.word_title }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>ユーザーID</strong>
        </div>
        <div class="col-9">
            <a href="{% url 'project:user_review_page' word.created_by.pk %}"> {{ word.created_by }} </a>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>本文</strong>
        </div>
        <div class="col-9">
            {{ word.word_text|linebreaksbr }}
        </div>
    </div>

    <hr>

    {% if word.photo %}
    <div class="row">
        <div class="col-3">
            <strong>写真</strong>
        </div>
        <div class="col-3">
            <img src="{{ word.photo.url }}" width="200" height="200"/>
        </div>
    </div>
    <hr>
    {% endif %}

    {% if user.is_authenticated %}
        {% if word.created_by != user %}

            {% for like in word.like_word.all %}
                {% if like == user %}
                    <button type="button" id="ajax-like" style="border:none;background:none">
                        <!-- すでにいいねしている時はfasクラス -->
                        <i class="fas fa-heart text-danger" id="like-icon"></i>
                    </button>
                    <span>いいね</span>
                {% else %}
                    {% if forloop.last == True %}
                        <button type="button" id="ajax-like" style="border:none;background:none">
                            <!-- いいねしていないときはfarクラス -->
                            <i class="far fa-heart text-danger" id="like-icon"></i>
                        </button>
                        <span>いいね</span>
                    {% endif %}
                {% endif %}
            {% empty %}
                <button type="button" id="ajax-like" style="border:none;background:none">
                    <!-- いいねしていないときはfarクラス -->
                    <i class="far fa-heart text-danger" id="like-icon"></i>
                </button>
                <span>いいね</span>
            {% endfor %}

        {% else %}
            <a class="btn btn-success mt-5 mb-3" href="{% url 'project:word_update' object.pk %}">編集</a>
            <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'project:word_delete' object.pk %}">削除</a>
            <br>
        {% endif %}
    {% endif %}
    <br>
    <a class="btn btn-success mt-5 mb-3" href="javascript:history.back()">前のページへ戻る</a>
</div>
{% endblock %}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>

{% block extrajs %}
<script type="text/javascript">
    // いいねボタンが押された時
    document.getElementById('ajax-like').addEventListener('click', e => {
        e.preventDefault();
        const url = '{% url "project:Ajax_ch_word" object.pk %}';
        fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
            'X-CSRFToken': '{{ csrf_token }}',
        },
        }).then(response => {
        return response.json();
        }).then(response => {
        const icon = document.getElementById('like-icon')
        // いいねした時はハートを塗る
        if (response.method == 'create') {
            icon.classList.remove('far')
            icon.classList.add('fas')
            icon.id = 'like-icon'
        } else {
            icon.classList.remove('fas')
            icon.classList.add('far')
            icon.id = 'like-icon'
        }
        }).catch(error => {
        console.log(error);
        });
    });
</script>
{% endblock %}