comparison_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),
    path('manage/', include('manage.urls'))
]

if settings_dev.DEBUG:
    urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .import views
from comparison_project import settings_common, settings_dev
from django.contrib.staticfiles.urls import static

app_name = 'project'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('word_detail/<int:pk>/', views.WordDetailView.as_view(), name="word_detail"),
    path('word_update/<int:pk>/', views.WordUpdateView.as_view(), name="word_update"),
    path('word_delete/<int:pk>/', views.WordDeleteView.as_view(), name="word_delete"),
    path('wordpost_create', views.WordCreateView.as_view(), name="wordpost_create"),
    path('wordreiew_list', views.WordReiewListView.as_view(), name="wordreiew_list"),
    path('wordreiew_list_like', views.WordReiewList_LikeView.as_view(), name="wordreiew_list_like"),
    path('search_advanced/', views.SearchAdvancedView.as_view(), name="search_advanced"),
    path('shop/<slug:category_slug>/', views.ProductListView.category_list, name='category_list'),
    path('product_list/', views.ProductListView.product_all, name="product_list"),
    path('product_detail/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('search_result/', views.get_queryset, name="search_result"),
    path('review/<int:pk>/', views.ReviewView.as_view(), name="review"),
    path('review_create/<slug:slug>/', views.ReviewCreateView.as_view(), name="review_create"),
    path('review_edit/<int:pk>/', views.ReviewEditView.as_view(), name="review_edit"), 
    path('review_delete/<int:pk>/', views.ReviewDeleteView.as_view(), name="review_delete"),
    path('user_review_page/<int:pk>/', views.UserReviewPageView.as_view(), name="user_review_page"),
    path('review_list/<int:pk>/', views.ReviewListView.as_view(), name="review_list"),
    path('word_list/<int:pk>/', views.WordListView.as_view(), name="word_list"),                                                                     
    path('wish_list/<int:pk>/', views.WishListView.as_view(), name="wish_list"),
    path('recently_view/<int:pk>/', views.RecentlyViewedView.as_view(), name="recently_view"),
    path('rank_list/', views.RankListView.as_view(), name="rank_list"),
    path('profile_edit/<int:pk>/', views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile_update/<int:pk>/', views.ProfileUpdateView.as_view(), name="profile_update"),
    path('Ajax_ch_word/<int:pk>/', views.Ajax_ch_word, name="Ajax_ch_word"),
    path('Ajax_ch_review/<int:pk>/', views.Ajax_ch_review, name="Ajax_ch_review"),
    path('Ajax_ch_product/<slug:slug>/', views.Ajax_ch_product, name="Ajax_ch_product"),
    path('review_product/<slug:slug>/', views.ReviewProductView.as_view(), name="review_product"),
]

if settings_dev.DEBUG:
    urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('shop/', views.IndexView.as_view(), name="shopindex"),
]

shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import CustomUser
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    """カテゴリーモデル"""
    category_name = models.CharField(verbose_name='カテゴリー', max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('project:category_list', args=[self.slug])

    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_name = models.CharField(verbose_name='商品名', max_length=255)
    description = models.TextField(verbose_name='詳細', max_length=500)
    image1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    image2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    image3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    price1 = models.DecimalField(verbose_name='楽天価格', max_digits=10, decimal_places=3, blank=True, null=True, default=0)
    link1 = models.CharField(verbose_name='楽天店舗に飛ぶ', max_length=500, blank=True, null=True)
    price2 = models.DecimalField(verbose_name='Amazon価格', max_digits=10, decimal_places=3, blank=True, null=True, default=0)
    link2 = models.CharField(verbose_name='Amazon店舗に飛ぶ', max_length=500, blank=True, null=True)
    price3 = models.DecimalField(verbose_name='Yahooショッピング価格', max_digits=10, decimal_places=3, blank=True, null=True, default=0)
    link3 = models.CharField(verbose_name='Yahooショッピング店舗に飛ぶ', max_length=500, blank=True, null=True)
    category = models.ForeignKey(Category, related_name='product', verbose_name='カテゴリー', on_delete=models.PROTECT)
    rating = models.IntegerField(verbose_name='商品評価', default='0',
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ])
    like_product = models.ManyToManyField(CustomUser, related_name='product_like', blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    product_brand = models.TextField(verbose_name='商品ブランド', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created_at',)

    def number_of_likes(self):
        return self.like_product.count()

    def get_absolute_url(self):
        return reverse('project:product_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name, allow_unicode=True)
        super(Product, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.product_name

    @property
    def imageURL(self):
        try:
            url = self.image1.url
        except:
            url = ''
        return url

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    title = forms.CharField(label ='タタイトル', max_length=200, required = True)

shop/views.py
from django.shortcuts import render
from django.views.generic import View
from .forms import SearchForm
import json
import requests

SEARCH_URL = 'https://app.rakuten.co.jp/services/api/BooksTotal/Search/20170404?format=json&applicationId=[1059665974949401126]'

def get_api_data(params):
    api = requests.get(SEARCH_URL, params=params).text
    result = json.loads(api)
    items = result['Items']
    return items

class IndexView(View):
    def get(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        return render(request, 'testindex.html', {
            'form':form,
        })
    

shop/templates/category.html
{% extends 'base.html' %}

{% load static %}
<title>{% block title %}{% endblock %} Product List</title>

{% block contents %}
<section class="page-section">
  <!--
    <div class="container px-4 px-lg-5">
        <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
            </div>
            <div class="carousel-inner">
            <div class="carousel-item">
                <img class="img-fluid rounded" src="{% static 'assets/img/carousels/1.jpg' %}" alt="img1" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
              
                <div class="container">
                <div class="carousel-caption">
                    <h1>東京</h1>
                    <p class="lead">東京都のシェアハウスはこちら。専門スタッフが週に最低1回、共用部分を清掃します。</p>
                </div>
                </div>
            </div>
            <div class="carousel-item active">
              <img class="img-fluid rounded" src="{% static 'assets/img/carousels/2.jpg' %}" alt="img2" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">

                <div class="container">
                <div class="carousel-caption">
                    <h1>千葉</h1>
                    <p class="lead">千葉県のシェアハウスはこちら。キッチン、洗濯機、シャワー、Wi-Fi等はご自由にお使いください。全て無料です。</p>
                </div>
                </div>
            </div>
            <div class="carousel-item">
              <img class="img-fluid rounded" src="{% static 'assets/img/carousels/3.jpg' %}" alt="img3" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">   

                <div class="container">
                <div class="carousel-caption">
                    <h1>神奈川</h1>
                    <p class="lead">神奈川県のシェアハウスはこちら。全室鍵付き個室＆プライベートをきちんと守れます。</p>
                </div>
                </div>
            </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    -->

  <div class="album py-5 bg-light">
    <div class="container">
      {% if not products %}
      <div class="col-12">何もないです。情報は見つけられません。</div>
      {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image1.url }}">

              <div class="card-body">
                <p class="card-text"></p>
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image1.url }}" alt="..." /></div>
            <!--<div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image2.url }}" alt="..." /></div>-->
            <div class="col-md-6">
                <h1 class="display-5 fw-bolder">{{ product.product_name }}</h1>
                <div class="fs-5 mb-5">
                    <!--<p><span class="lead"></span>商品詳細:{{ product.description }}</span> </p>-->
                    <p><span>Amazon価格:{{ product.price1 }}</span></p>
                    <p><span>Amazon店舗に飛ぶ:{{ product.link1 }}</span></p>
                    
                </div>
            </div>
            <div class="col-md-6">
                <p class="lead">{{ product.description }}</p>
            </div>
        </div>
    </div>
</section>
<!-- Carousel -->
<div id="demo" class="carousel slide" data-bs-ride="carousel">

    <!-- Indicators/dots -->
    <div class="carousel-indicators">
    <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
    <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
    <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
    </div>

    <!-- The slideshow/carousel -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ product.image1.url }}" alt="img1" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="{{ product.image2.url }}" alt="img2" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="{{ product.image3.url }}" alt="img3" class="d-block w-100">
        </div>
    </div>

    <!-- Left and right controls/icons -->
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
    </button>
</div>

<div class="card mb-4">
    <div class="card-header">レビュー一覧</div>
    <div class="card-body">
        {% for product in products %}
        <p style="text-align:left">#{{ forloop.counter }}<a href="{% url 'project:product_detail' %}">{{ product.product_name|truncatechars:20 }}</a></p>
        <br>
        {% endfor %}
    </div>
    <a href="{% url 'project:rank_list'%}">もっと見る</a>
</div>
{% endblock %} 

shop/templates/product_list.html
{% extends 'base.html' %}

{% load static %}
<title>{% block title %}{% endblock %} Product List</title>

{% block contents %}

  <!--<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">マップハウジング</h1>
        <p class="lead text-muted">世界最大の都市へのヒントと秘密はすぐにわかります。銀行システムをナビゲートする、どの電話プランを取得する必要があるかを把握する、
            公共交通機関で自分をだまされないようにする方法を知るなど、私たちは必要不可欠なものを手に入れました。ここで東京の専門家になります。</p>
        <p>
        {% if user.is_authenticated %}
        {% else %}
        <a href="{% url 'account_signup' %}" class="btn btn-outline-primary my-2">今すぐに登録</a>
        <a href="{% url 'account_login' %}" class="btn btn-primary my-2">ログイン</a>
        {% endif %}
        </p>
      </div>
    </div>
  </section>-->
  <div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <br>
            <h3>新着商品</h3>
            {% if not products %}
            <div class="col-12">何もないです。情報は見つけられません。</div>
            {% else %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
              {% for product in products %}
              <div class="col">
                <div class="card shadow-sm">
                  <img class="img-fluid" alt="Responsive image" src="{{ product.image1.url }}">

                  <div class="card-body">
                    <p class="card-text"></p>
                    <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.product_name }}</a>
                    <div class="d-flex justify-content-between align-items-center">
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            {% endif %}

            <!-- ランキング　-->
            <div class="card mb-4">
                <div class="card-header">ランキング</div>
                    <div class="card-body">
                        {% for ranking in rank_list %}
                            <li><a href="{% url 'project:商品詳細ページ' project.pk %}">{{ ranking.product_name }}</a></li>
                        {% endfor %}
                    </div>
                </div>
            </div>            

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/testindex.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% load static %}

{% block title %}API test site{% endblock %}

{% block contents %}
<div class="text-center my-5">
    <form method="post">
        {% csrf_token %}
        <div class="align-items-center">
            {% render_field form.title class="form-control" placeholder="キーワードから探す" %}
            <button class="btn btn-primary mt-2" type="submit">検索</button>
        </div>
    </form>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}